name: GSFH
author: lz5509
description: Geyser SlimeFun Heads
main: me.lz5509.geyserslimefunhead.GSFH
website: https://github.com/Slimefun/Addon-Template
version: ${project.version}
api-version: 1.14
depend:
- Slimefun
- Geyser-Spigot
commands:
  gsfh:
      description: GSFH COMMANDS
      usage: /gsfh
      aliases: [geyserslimefunheads, geyserslimefunhead]
      permission: gsfh